import {
  openai,
  createAgent,
  createTool,
  createNetwork,
  type Tool,
  type AgentResult,
  type TextMessage,
} from "@inngest/agent-kit";
import { Sandbox } from "@e2b/code-interpreter";
import z from "zod";
import { PROMPT } from "@/prompt";
import { prisma } from "@/lib/db";

interface AgentState {
  summary: string;
  files: { [path: string]: string };
}

async function getSandbox(sandboxId: string) {
  const sandbox = await Sandbox.connect(sandboxId);
  return sandbox;
}

function lastAssistantTextMessageContent(result: AgentResult) {
  const lastAssistantTextMessageIndex = result.output.findLastIndex(
    (message) => message.role === "assistant",
  );

  const message = result.output[lastAssistantTextMessageIndex] as
    | TextMessage
    | undefined;

  return message?.content
    ? typeof message.content === "string"
      ? message.content
      : message.content.map((c) => c.text).join("")
    : undefined;
}

export async function generateProject(input: {
  value: string;
  projectId: string;
}) {
  const sandboxId = await (async () => {
    let sandbox;
    const templateId = process.env.E2B_TEMPLATE_ID || "vibe-nextjs-test-4";

    try {
      sandbox = await Sandbox.create(templateId);
    } catch (e) {
      console.warn(
        `Failed to load custom template "${templateId}". Falling back to base sandbox. Note: This may lack pre-installed dependencies. Error: ${e}`
      );
      sandbox = await Sandbox.create("base");

      // If we're falling back to base, we need to ensure the environment is ready
      // The base sandbox doesn't have the Next.js app structure, so we create a skeleton
      // This prevents "NotFoundError" when the agent tries to read files
      const hasPage = await sandbox.files.exists("app/page.tsx");
      if (!hasPage) {
        await sandbox.files.write(
          "package.json",
          JSON.stringify(
            {
              name: "vibe-app",
              version: "0.1.0",
              scripts: {
                dev: "next dev",
                build: "next build",
                start: "next start",
              },
              dependencies: {
                next: "15.3.3",
                react: "19.0.0",
                "react-dom": "19.0.0",
                "lucide-react": "latest",
                clsx: "latest",
                "tailwind-merge": "latest",
              },
              devDependencies: {
                typescript: "latest",
                "@types/node": "latest",
                "@types/react": "latest",
                "@types/react-dom": "latest",
                postcss: "latest",
                tailwindcss: "latest",
              },
            },
            null,
            2
          )
        );

        await sandbox.files.write(
          "tsconfig.json",
          JSON.stringify(
            {
              compilerOptions: {
                lib: ["dom", "dom.iterable", "esnext"],
                allowJs: true,
                skipLibCheck: true,
                strict: true,
                noEmit: true,
                esModuleInterop: true,
                module: "esnext",
                moduleResolution: "bundler",
                resolveJsonModule: true,
                isolatedModules: true,
                jsx: "preserve",
                incremental: true,
                plugins: [{ name: "next" }],
                paths: {
                  "@/*": ["./*"],
                },
              },
              include: [
                "next-env.d.ts",
                "**/*.ts",
                "**/*.tsx",
                ".next/types/**/*.ts",
              ],
              exclude: ["node_modules"],
            },
            null,
            2
          )
        );

        await sandbox.files.write(
          "app/layout.tsx",
          `
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
          `.trim()
        );

        await sandbox.files.write(
          "app/page.tsx",
          `
export default function Home() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen py-2">
      <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
        <h1 className="text-6xl font-bold">
          Welcome to <a className="text-blue-600" href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  );
}
          `.trim()
        );

        await sandbox.files.write(
          "lib/utils.ts",
          `
import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
          `.trim()
        );

        await sandbox.files.write(
          "app/globals.css",
          `
@tailwind base;
@tailwind components;
@tailwind utilities;
          `.trim()
        );

        console.log("Installing dependencies...");
        await sandbox.commands.run("npm install", {
          timeoutMs: 300000, // 5 minutes
        });

        console.log("Starting dev server...");
        await sandbox.commands.run("npm run dev > /dev/null 2>&1 &");
      }
    }

    // Ensure the server is running on port 3000
    // We check if port 3000 is open. If not, we start the server.
    // This covers cases where the custom template failed to start the server or it crashed.
    console.log("Ensuring server is running...");
    await sandbox.commands.run("if ! curl -s http://localhost:3000 > /dev/null; then npm run dev > /dev/null 2>&1 & fi");

    return sandbox.sandboxId;
  })();

  const codeAgent = createAgent<AgentState>({
    name: "code-agent",
    description: "An expert coding agent",
    system: PROMPT,
    model: openai({
      model: "moonshotai/kimi-k2:free",
      apiKey: process.env.OPENROUTER_API_KEY,
      baseUrl: "https://openrouter.ai/api/v1",
    }),
    tools: [
      createTool({
        name: "terminal",
        description: "Use the terminal to run commands",
        parameters: z.object({
          command: z.string(),
        }),
        handler: async ({ command }) => {
          const buffers = { stdout: "", stderr: "" };

          try {
            const sandbox = await getSandbox(sandboxId);
            const result = sandbox.commands.run(command, {
              onStdout: (data: string) => {
                buffers.stdout += data;
              },
              onStderr: (data: string) => {
                buffers.stderr += data;
              },
            });
            return (await result).stdout;
          } catch (e) {
            console.error(
              `Command failed: ${e} \nstdout: ${buffers.stdout}\nstderror: ${buffers.stderr}`
            );
            return `Command failed: ${e} \nstdout: ${buffers.stdout}\nstderror: ${buffers.stderr}`;
          }
        },
      }),
      createTool({
        name: "createOrUpdateFiles",
        description: "Create or update files in the sandbox",
        parameters: z.object({
          files: z.array(
            z.object({
              path: z.string(),
              content: z.string(),
            }),
          ),
        }),
        handler: async (
          { files },
          { network }: Tool.Options<AgentState>,
        ) => {
          try {
            const updatedFiles = network.state.data.files || {};
            const sandbox = await getSandbox(sandboxId);
            for (const file of files) {
              await sandbox.files.write(file.path, file.content);
              updatedFiles[file.path] = file.content;
            }

            if (typeof updatedFiles === "object") {
              network.state.data.files = updatedFiles;
            }

            return updatedFiles;
          } catch (e) {
            return "Error: " + e;
          }
        },
      }),
      createTool({
        name: "readFiles",
        description: "Read files from the sandbox",
        parameters: z.object({
          files: z.array(z.string()),
        }),
        handler: async ({ files }) => {
          try {
            const sandbox = await getSandbox(sandboxId);
            const contents = [];
            for (const file of files) {
              // Prevent hallucination to ensure file exists
              const content = await sandbox.files.read(file);
              contents.push({ path: file, content });
            }
            return JSON.stringify(contents);
          } catch (e) {
            return "Error: " + e;
          }
        },
      }),
    ],
    lifecycle: {
      onResponse: async ({ result, network }) => {
        const lastAssistantMessageText =
          lastAssistantTextMessageContent(result);

        if (lastAssistantMessageText && network) {
          if (lastAssistantMessageText.includes("<task_summary>")) {
            network.state.data.summary = lastAssistantMessageText;
          }
        }

        return result;
      },
    },
  });

  const network = createNetwork<AgentState>({
    name: "coding-agent-network",
    agents: [codeAgent],
    maxIter: 15,
    router: async ({ network }) => {
      const summary = network.state.data.summary;
      if (summary) {
        return;
      }
      return codeAgent;
    },
  });

  const result = await network.run(input.value);

  const hasSummary = !!result.state.data.summary;
  const hasFiles = Object.keys(result.state.data.files || {}).length > 0;
  const isError = !hasSummary || !hasFiles;

  if (isError) {
    console.error(
      `Agent failed to produce a valid result. Has Summary: ${hasSummary}, Has Files: ${hasFiles}`
    );
  }

  const sandboxUrl = await (async () => {
    const sandbox = await getSandbox(sandboxId);
    const host = sandbox.getHost(3000);
    return `https://${host}`;
  })();

  try {
    if (isError) {
      return await prisma.message.create({
        data: {
          projectId: input.projectId,
          content: "Something went wrong. Please try again.",
          role: "ASSISTANT",
          type: "ERROR",
        },
      });
    }

    return await prisma.message.create({
      data: {
        projectId: input.projectId,
        content: result.state.data.summary,
        role: "ASSISTANT",
        type: "RESULT",
        fragment: {
          create: {
            sandboxUrl: sandboxUrl,
            title: "Fragment",
            files: result.state.data.files,
          },
        },
      },
    });
  } catch (e) {
    console.error("Database save failed:", e);
    throw e;
  }
}
